name: Hello World
on: 
  pull_request:
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: push tag
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_DATE: ${{ github.event.pull_request.created_at }}
        run: |
            TAG_VERSION="R.0 $PR_DATE PROD Release"
            git tag $TAG_VERSION
            git push origin $TAG_VERSION
